### ISSUE TITLE
Group push messages

### ISSUE THREAD

**Issue by mazzcris** [mazzcris/wormhole#1]
Group push messages so that this:
04oct: In MAZZCRIS/SORTELLO, MAZZCRIS pushed 1 commits to REFS/HEADS/UI-RESTYLE
04oct: In MAZZCRIS/SORTELLO, MAZZCRIS pushed 1 commits to REFS/HEADS/UI-RESTYLE
04oct: In MAZZCRIS/SORTELLO, MAZZCRIS pushed 1 commits to REFS/HEADS/UI-RESTYLE
04oct: In MAZZCRIS/SORTELLO, MAZZCRIS pushed 1 commits to REFS/HEADS/UI-RESTYLE
04oct: In MAZZCRIS/SORTELLO, MAZZCRIS pushed 1 commits to REFS/HEADS/UI-RESTYLE

Turns into this:
04oct: In MAZZCRIS/SORTELLO, MAZZCRIS pushed 5 commits to REFS/HEADS/UI-RESTYLE

**Comment by AlithAnar** [comment]
I can take this!

**Comment by AlithAnar** [comment]
PR created

**Comment by mazzcris** [comment]
Merged, thanks!
